initial commit
AleksandrPok/TaxiService pull request #7
Opened 2021-01-25 13:56 UTC by AleksandrPok

2021-01-25 15:35 UTC, Max-Pochepets approved these changes
👍

2021-01-25 15:35 UTC, Max-Pochepets commented on src/main/java/taxi/filter/AuthenticationFilter.java
> +        if (req.getSession().getAttribute("driver_id") == null) {
TOTHINK: what if logged in driver deletes themselves?

2021-01-25 17:25 UTC, RomanDubovskyi requested changes
don't forget to fix points, mentioned in the chat

2021-01-25 17:25 UTC, RomanDubovskyi commented on src/main/java/taxi/filter/AuthenticationFilter.java
> +    private final DriverService driverService = (DriverService)
do we use it here?

2021-01-26 13:19 UTC, RomanDubovskyi approved these changes

2021-01-26 16:05 UTC, merged